### ISSUE TITLE
A-Cloud - Upload thumbnail image with packages

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/anaconda-client#329]
Request from Conda-Forge and also our Mosaic team - use case: they need to get an image uploaded with a package so that it can appear in Navigator as an icon (when the package is an application)

Should use the same syntax as notebook upload. If already specified in the meta.yml file, then just include that.

**Comment by stephenakearns** [comment]
@goanpeca and @dsludwig - please add additional requirements/details in the description or comments.

**Comment by goanpeca** [comment]
I will add a bit more context.

# Anaconda Cloud
Currently Navigator has no straightforward way of having access to the icon/image for a given package that has been declared as an application (meta.yaml, app section). Although the meta yaml defines the location of the icon and included this is include in the zipped package file, when uploading to Anaconda Cloud, the image is not stored separately for easy access retrieval. Notebooks do allow for thumbnails so we could leverage the code that already exists in that area so that the process of uploading a package to anaconda cloud would actually upload (automatically) the image associated to it (if any).

Talking with @dsludwig about how to handle this, we could split the work in the different parts. 

## Anaconda Client
When using anaconda client to upload a package we could inspect the tar file and look for the meta.yaml and grab the icon as needed and automatically upload this as part of the package. The "problem" here is that anaconda client now needs to handle this extra logic, so it needs to be smarter about stuff. Another option would be to make conda build give the location of the icon and the package as part of the build process... (**Now you can upload to cloud using bla bla....**). This would require  changing also conda-build.

## Anaconda Cloud
Anaconda cloud  would then receive either a tar file alone or a tar file plus an image.

### Questions
- Is an image saved by package version or by pacakge namespace... just wondering
- Should the changes include conda-build so that anaconda client should only worry about looking for an image with the same name as the package being upload? This would keep the logic on anaconda client simple, and the changes (already in charge of parsing the meta.yaml) would be minimal.

Comments @dsludwig, @srossross ?

# Repo Continuum
We still would need to figure how to handle repo.continuum.io. The same way metadata is handled, we could provide the images in a separate location based on package name?
- `repo.continuum.io/pkgs/images/spyder`
- `repo.continuum.io/pkgs/images/glueviz`  ...

@ilanschnell 

----

Currently we have icons within the navigator repo for the applications available on repo.continuum.io, but clearly this methods is not future proof, as we would need to update Navigator every time there is a new release of Anaconda Distribution that

**Comment by MulticastMatt** [comment]
@goanpeca what's the latest here?
