### ISSUE TITLE
Disallow uploading of empty project.yml 

### ISSUE THREAD

**Issue by quasiben** [Anaconda-Platform/anaconda-client#334]
If project.yml contains no data `anaconda-client` will still attempt an upload.  We should prevent this behavior by at least checking project.yml has the `name` key defined -- perhaps other keys as well.

cc @havocp

**Comment by havocp** [comment]
A missing project.yml is supposed to be allowed at the moment, because everything has a default value (the default name is the directory name). With https://github.com/Anaconda-Platform/anaconda-project/issues/276 an empty project.yml will no longer be valid and in this scenario we'll instead ask the user if they want to create one. All of this should be transparent to anaconda-client though, it'll be taken care of in the project API that anaconda-client is using. I wouldn't put any checks in anaconda-client itself.

**Comment by stephenakearns** [comment]
Hi Team - closing this item in favor of working on #276 - if needed, please reopen and clarify what's next for this specific issue, distinct from the one mentioned above.
