### ISSUE TITLE
anaconda copy not working correctly

### ISSUE THREAD

**Issue by astrofrog** [Anaconda-Platform/anaconda-client#413]
The following command gives an error that doesn't make sense:

```
$ anaconda copy --from-channel conda-forge --to-channel astrofrog glueviz
Using Anaconda API: https://api.anaconda.org
[UserError] Label conda-forge does not exist
	please choose from: main
```

conda-forge is a channel, not a label (I am not using --from-label but --from-channel)

**Comment by j0hn** [comment]
The `copy` command interface is a little bit confussing. `labels` used to be called `channels` and that's why the `--from-channel/--to-channel` options are deprecated. 

What you need to use is the `spec` where the format is `user/package/version[/filename]`

For example, on your case you would want to do:

```bash
$ anaconda copy conda-forge/glueviz/0.10.4 --to-owner astrofrog
```

**Comment by msarahan** [comment]
I ran into this also, with exactly the same approach as @astrofrog.  Thanks for documenting a proper example, but please simplify the CLI, or make what I see as "intuitive" also work.

**Comment by goanpeca** [comment]
@electronwill is this currently documented somewhere :-p ?

**Comment by electronwill** [comment]
No, anaconda-client is mentioned at https://docs.anaconda.com/anaconda-repository/commandreference and https://docs.anaconda.com/anaconda-cloud/commandreference but neither discusses this. Would you like us to add items in the Repo and Cloud Troubleshooting pages?

**Comment by goanpeca** [comment]
maybe? thoughts @csoja?

**Comment by csoja** [comment]
Yes, it seems to me like this should be explained in the documentation.

**Comment by electronwill** [comment]
Turns out there were better places than just Troubleshooting to add the info in both Cloud and Repo.

Leaving this issue open for removing the flags in 1.7, but the documentation component should be complete now.

published & checked:
https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages
https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/
https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/copy-pkg

**Comment by goanpeca** [comment]
Awesome @electronwill :-), so closing then!
